Update ios.yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -1,42 +1,114 @@
-name: iOS starter workflow
+name: CI-Test
 
 on:
-  pull_request:
-    branches: [ develop ]
+  push:
+    branches: [ feature/CITest/2.0.1 ]
+  #pull_request:
+  #  branches: [ develop ]
+  #  types: [ opened ]
 
 jobs:
-  build:
-    name: Build and Test default scheme using any available iPhone simulator
+  ### develop env ci (build & unit test)
+  DEVELOP-CI:
     runs-on: macos-12.2.1
+    #runs-on: macos-latest
+    #runs-on: ubuntu-latest
+    env:
+      TARGET_ENV: Debuh
+      XCWORKSPACE: gitProject.xcodepro
+      #PROJECT: pineapp.xcodeproj
+      SCHEME: gitProject
+      #CONFIGURATION: Debug
+      DESTINATION: platform=iOS Simulator,name=iPhone 13,OS=15.0
+      #MATTERMOST_WEBHOOK_URL: https://mattermost.hwikx.com/hooks/cip4am3x4f885b7ayt4gu5ug1a
+      #MATTERMOST_WEBHOOK_CHANNEL: private_mattermost_chat_test
+
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Set Default Scheme
-        run: |
-          scheme_list=$(xcodebuild -list -json | tr -d "\n")
-          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
-          echo $default | cat >default
-          echo Using default scheme: $default
-      - name: Build
-        env:
-          scheme: ${{ 'default' }}
-          platform: ${{ 'iOS Simulator' }}
-        run: |
-          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
-          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
-          if [ $scheme = default ]; then scheme=$(cat default); fi
-          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
-          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
-          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
-      - name: Test
-        env:
-          scheme: ${{ 'default' }}
-          platform: ${{ 'iOS Simulator' }}
-        run: |
-          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
-          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
-          if [ $scheme = default ]; then scheme=$(cat default); fi
-          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
-          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
-          xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
+    - uses: actions/checkout@v2
+
+    #- name: Send CI Start Message
+    #  run: |
+    #    curl -i -X POST ${{ env.MATTERMOST_WEBHOOK_URL }} \
+    #    -H 'Content-Type: application/json' \
+    #    --data '{"channel":"${{ env.MATTERMOST_WEBHOOK_CHANNEL }}","attachments":[{"color":"#00bfff","text":"##### [iOS CI Action Start]
+    #    `Project Name` : ${{ github.repository }} (Run Number: ${{ github.run_number }})
+    #    `Target Env` : ${{ env.TARGET_ENV }}
+    #    `PR Number` : ${{ github.ref_name }}
+    #    `Request Uername` : ${{ github.actor }}
+    #    `Request Type` : ${{ github.event_name }}"}]}'
+    
+    - name: Check Xcode
+      run: ls -n /Applications/ | grep Xcode
+    
+    #- name: Setup - Xcode
+    #  run: sudo xcode-select -s /Applications/Xcode_13.0.app/Contents/Developer
+
+    #- name: Pod Update
+    #  run: |
+    #    pod update
+    #    pod repo update
+
+    #- name: Pod Install
+    #  run: pod install --repo-update --clean-install
+
+    - name: Build
+      run: |
+        xcodebuild clean test -workspace "$XCWORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION"
+        echo $?
+    #- name: Comment To PR (Success)
+    #  uses: actions/github-script@v5.0.0
+    #  with:
+    #    github-token: ${{ github.token }}
+    #    script: |
+    #      github.rest.issues.createComment({
+    #        issue_number: context.issue.number,
+    #        owner: context.repo.owner,
+    #        repo: context.repo.repo,
+    #        body: 'Code test completed successfully!'
+    #      })
+
+
+    - name: CI Finish Message (Success)
+      run: |
+        echo $?
+    #    curl -i -X POST ${{ env.MATTERMOST_WEBHOOK_URL }} \
+    #    -H 'Content-Type: application/json' \
+    #    --data '{"channel":"${{ env.MATTERMOST_WEBHOOK_CHANNEL }}","attachments":[{"color":"#44ff00","text":"##### [iOS CI Action Success]
+    #    `Project Name` : ${{ github.repository }} (Run Number: ${{ github.run_number }})
+    #    `Target Env` : ${{ env.TARGET_ENV }}
+    #    `PR Number` : ${{ github.ref_name }}
+    #    `Request Uername` : ${{ github.actor }}
+    #    `CI Result` : ${{ job.status }}"}]}'
+    ### Only Comment to PR (Not Used)
+    ##- if: failure()
+    ##  name: Comment To PR (Failed)
+    ##  uses: actions/github-script@v5.0.0
+    ##  with:
+    ##    github-token: ${{ github.token }}
+    ##    script: |
+    ##      github.rest.issues.createComment({
+    ##        issue_number: context.issue.number,
+    ##        owner: context.repo.owner,
+    ##        repo: context.repo.repo,
+    ##        body: 'Code test failed!! Check Again!! GitAction Number is [ ${{ github.run_number }} ]'
+    ##      })
+
+
+    - if: failure()
+      name: CI Finish Message (Failed)
+      run: |
+    #    curl -i -X POST ${{ env.MATTERMOST_WEBHOOK_URL }} \
+    #    -H 'Content-Type: application/json' \
+    #    --data '{"channel":"${{ env.MATTERMOST_WEBHOOK_CHANNEL }}","attachments":[{"color":"#ff0000","text":"##### [iOS CI Action Failed]
+    #    `Project Name` : ${{ github.repository }} (Run Number: ${{ github.run_number }})
+    #    `Target Env` : ${{ env.TARGET_ENV }}
+    #    `PR Number` : ${{ github.ref_name }}
+    #    `Request Uername` : ${{ github.actor }}
+    #    `CI Result` : ${{ job.status }}"}]}'
+    ### Comment to PR and Close PR
+    #- if: failure()
+    #  name: Comment To PR (Failed)
+    #  uses: peter-evans/close-pull@v1.1.3
+    #  with:
+    #    comment: 'Code test failed!! Check Again!! GitAction Number is [ ${{ github.run_number }} ]'
